-- Append top-200 colleges to the list. Safe to run multiple times —
-- `ON CONFLICT (id) DO NOTHING` skips any id that's already in the table.
--
-- ID conventions:
--   - For schools whose short id is already canonical in your DB
--     (mit, caltech, ucla, uc-berkeley, uc-san-diego), those exact ids
--     are used so there's no duplicate row.
--   - Everything else uses a kebab-case slug derived from the full name.
--   - ON CONFLICT DO NOTHING means re-running this SQL won't create
--     duplicates even if the slug happens to match.
--
-- Acceptance rate and SAT range are left NULL for schools we don't have
-- exact current data for. You can backfill in Supabase Table Editor
-- whenever convenient.

insert into public.colleges (id, name, location, acceptance_rate, sat_range_low, sat_range_high) values
  ('princeton-university', 'Princeton University', 'Princeton, NJ', 0.05, 1510, 1580),
  ('stanford-university', 'Stanford University', 'Stanford, CA', 0.04, 1500, 1570),
  ('mit', 'Massachusetts Institute of Technology', 'Cambridge, MA', 0.04, 1520, 1580),
  ('yale-university', 'Yale University', 'New Haven, CT', 0.05, 1510, 1580),
  ('uc-berkeley', 'University of California, Berkeley', 'Berkeley, CA', 0.11, 1410, 1540),
  ('columbia-university', 'Columbia University', 'New York, NY', 0.04, 1510, 1560),
  ('university-of-pennsylvania', 'University of Pennsylvania', 'Philadelphia, PA', 0.06, 1510, 1560),
  ('harvard-university', 'Harvard University', 'Cambridge, MA', 0.03, 1510, 1580),
  ('rice-university', 'Rice University', 'Houston, TX', 0.08, 1500, 1560),
  ('cornell-university', 'Cornell University', 'Ithaca, NY', 0.07, 1470, 1560),
  ('northwestern-university', 'Northwestern University', 'Evanston, IL', 0.07, 1500, 1560),
  ('johns-hopkins-university', 'Johns Hopkins University', 'Baltimore, MD', 0.07, 1520, 1560),
  ('ucla', 'University of California, Los Angeles', 'Los Angeles, CA', 0.09, 1360, 1550),
  ('university-of-chicago', 'University of Chicago', 'Chicago, IL', 0.05, 1520, 1580),
  ('vanderbilt-university', 'Vanderbilt University', 'Nashville, TN', 0.07, 1490, 1560),
  ('dartmouth-college', 'Dartmouth College', 'Hanover, NH', 0.06, 1500, 1560),
  ('williams-college', 'Williams College', 'Williamstown, MA', null, null, null),
  ('brown-university', 'Brown University', 'Providence, RI', 0.05, 1500, 1570),
  ('claremont-mckenna-college', 'Claremont McKenna College', 'Claremont, CA', null, null, null),
  ('duke-university', 'Duke University', 'Durham, NC', 0.06, 1510, 1560),
  ('uc-san-diego', 'University of California, San Diego', 'La Jolla, CA', 0.24, 1360, 1530),
  ('caltech', 'California Institute of Technology', 'Pasadena, CA', 0.03, 1540, 1580),
  ('wellesley-college', 'Wellesley College', 'Wellesley, MA', null, null, null),
  ('amherst-college', 'Amherst College', 'Amherst, MA', null, null, null),
  ('bowdoin-college', 'Bowdoin College', 'Brunswick, ME', null, null, null),
  ('university-of-florida', 'University of Florida', 'Gainesville, FL', 0.23, 1350, 1490),
  ('swarthmore-college', 'Swarthmore College', 'Swarthmore, PA', null, null, null),
  ('university-of-southern-california', 'University of Southern California', 'Los Angeles, CA', 0.12, 1450, 1540),
  ('university-of-michigan-ann-arbor', 'University of Michigan, Ann Arbor', 'Ann Arbor, MI', 0.18, 1360, 1530),
  ('washington-university-st-louis', 'Washington University in St. Louis', 'St. Louis, MO', 0.11, 1520, 1560),
  ('unc-chapel-hill', 'University of North Carolina, Chapel Hill', 'Chapel Hill, NC', 0.17, 1380, 1520),
  ('georgetown-university', 'Georgetown University', 'Washington, DC', 0.12, 1410, 1550),
  ('emory-university', 'Emory University', 'Atlanta, GA', 0.11, 1450, 1540),
  ('university-of-virginia', 'University of Virginia', 'Charlottesville, VA', 0.19, 1400, 1530),
  ('university-of-california-santa-barbara', 'University of California, Santa Barbara', 'Santa Barbara, CA', null, null, null),
  ('brigham-young-university', 'Brigham Young University', 'Provo, UT', null, null, null),
  ('pomona-college', 'Pomona College', 'Claremont, CA', null, null, null),
  ('georgia-institute-of-technology', 'Georgia Institute of Technology', 'Atlanta, GA', 0.17, 1480, 1540),
  ('university-of-california-irvine', 'University of California, Irvine', 'Irvine, CA', 0.26, 1320, 1510),
  ('university-of-illinois-urbana-champaign', 'University of Illinois, Urbana-Champaign', 'Champaign, IL', 0.43, 1370, 1530),
  ('university-of-maryland-college-park', 'University of Maryland, College Park', 'College Park, MD', 0.44, 1380, 1530),
  ('university-of-notre-dame', 'University of Notre Dame', 'Notre Dame, IN', 0.13, 1440, 1550),
  ('university-of-california-davis', 'University of California, Davis', 'Davis, CA', 0.37, 1280, 1500),
  ('university-of-washington', 'University of Washington, Seattle', 'Seattle, WA', null, null, null),
  ('colgate-university', 'Colgate University', 'Hamilton, NY', null, null, null),
  ('university-of-texas-austin', 'University of Texas, Austin', 'Austin, TX', 0.31, 1240, 1470),
  ('washington-and-lee-university', 'Washington and Lee University', 'Lexington, VA', null, null, null),
  ('davidson-college', 'Davidson College', 'Davidson, NC', null, null, null),
  ('new-york-university', 'New York University', 'New York, NY', 0.12, 1470, 1560),
  ('university-of-wisconsin-madison', 'University of Wisconsin, Madison', 'Madison, WI', 0.49, 1340, 1500),
  ('middlebury-college', 'Middlebury College', 'Middlebury, VT', null, null, null),
  ('tufts-university', 'Tufts University', 'Medford, MA', null, null, null),
  ('boston-university', 'Boston University', 'Boston, MA', 0.14, 1420, 1520),
  ('wesleyan-university', 'Wesleyan University', 'Middletown, CT', null, null, null),
  ('william-and-mary', 'William & Mary', 'Williamsburg, VA', 0.33, 1370, 1510),
  ('barnard-college', 'Barnard College', 'New York, NY', null, null, null),
  ('cal-poly-slo', 'Cal Poly SLO', 'San Luis Obispo, CA', null, null, null),
  ('carnegie-mellon-university', 'Carnegie Mellon University', 'Pittsburgh, PA', 0.11, 1510, 1560),
  ('boston-college', 'Boston College', 'Chestnut Hill, MA', 0.16, 1440, 1530),
  ('lafayette-college', 'Lafayette College', 'Easton, PA', null, null, null),
  ('santa-clara-university', 'Santa Clara University', 'Santa Clara, CA', null, null, null),
  ('university-of-georgia', 'University of Georgia', 'Athens, GA', null, null, null),
  ('purdue-university', 'Purdue University', 'West Lafayette, IN', 0.53, 1290, 1480),
  ('lehigh-university', 'Lehigh University', 'Bethlehem, PA', null, null, null),
  ('florida-state-university', 'Florida State University', 'Tallahassee, FL', null, null, null),
  ('hamilton-college', 'Hamilton College', 'Clinton, NY', null, null, null),
  ('george-washington-university', 'George Washington University', 'Washington, DC', null, null, null),
  ('nc-state-raleigh', 'North Carolina State University, Raleigh', 'Raleigh, NC', null, null, null),
  ('olin-college-of-engineering', 'Franklin W. Olin College of Engineering', 'Needham, MA', null, null, null),
  ('texas-am-university', 'Texas A&M University, College Station', 'College Station, TX', 0.64, 1240, 1430),
  ('trinity-college-ct', 'Trinity College (CT)', 'Hartford, CT', null, null, null),
  ('haverford-college', 'Haverford College', 'Haverford, PA', null, null, null),
  ('northeastern-university', 'Northeastern University', 'Boston, MA', null, null, null),
  ('cuny-baruch-college', 'CUNY, Baruch College', 'New York, NY', null, null, null),
  ('university-of-minnesota-twin-cities', 'University of Minnesota, Twin Cities', 'Minneapolis, MN', null, null, null),
  ('binghamton-university-suny', 'Binghamton University, SUNY', 'Binghamton, NY', null, null, null),
  ('san-diego-state-university', 'San Diego State University', 'San Diego, CA', null, null, null),
  ('cooper-union', 'Cooper Union', 'New York, NY', null, null, null),
  ('rutgers-university-new-brunswick', 'Rutgers University', 'New Brunswick, NJ', 0.60, 1240, 1450),
  ('bates-college', 'Bates College', 'Lewiston, ME', null, null, null),
  ('grinnell-college', 'Grinnell College', 'Grinnell, IA', null, null, null),
  ('university-of-miami', 'University of Miami (FL)', 'Coral Gables, FL', 0.28, 1350, 1490),
  ('virginia-tech', 'Virginia Tech', 'Blacksburg, VA', null, null, null),
  ('stony-brook-university-suny', 'Stony Brook University, SUNY', 'Stony Brook, NY', null, null, null),
  ('university-of-connecticut', 'University of Connecticut', 'Storrs, CT', null, null, null),
  ('ohio-state-university', 'Ohio State University', 'Columbus, OH', 0.53, 1310, 1460),
  ('villanova-university', 'Villanova University', 'Villanova, PA', null, null, null),
  ('wake-forest-university', 'Wake Forest University', 'Winston-Salem, NC', null, null, null),
  ('csu-long-beach', 'California State University, Long Beach', 'Long Beach, CA', null, null, null),
  ('michigan-state-university', 'Michigan State University', 'East Lansing, MI', null, null, null),
  ('university-of-rochester', 'University of Rochester', 'Rochester, NY', 0.39, 1410, 1530),
  ('indiana-university-bloomington', 'Indiana University, Bloomington', 'Bloomington, IN', null, null, null),
  ('bucknell-university', 'Bucknell University', 'Lewisburg, PA', null, null, null),
  ('university-of-utah', 'University of Utah', 'Salt Lake City, UT', null, null, null),
  ('trinity-university-tx', 'Trinity University (TX)', 'San Antonio, TX', null, null, null),
  ('babson-college', 'Babson College', 'Babson Park, MA', null, null, null),
  ('university-of-california-riverside', 'University of California, Riverside', 'Riverside, CA', null, null, null),
  ('clemson-university', 'Clemson University', 'Clemson, SC', null, null, null),
  ('southern-methodist-university', 'Southern Methodist University', 'Dallas, TX', 0.47, 1340, 1500),
  ('csu-fullerton', 'California State University, Fullerton', 'Fullerton, CA', null, null, null),
  ('university-of-richmond', 'University of Richmond', 'Richmond, VA', null, null, null),
  ('vassar-college', 'Vassar College', 'Poughkeepsie, NY', null, null, null),
  ('college-of-the-holy-cross', 'College of the Holy Cross', 'Worcester, MA', null, null, null),
  ('university-of-colorado-boulder', 'University of Colorado, Boulder', 'Boulder, CO', null, null, null),
  ('brandeis-university', 'Brandeis University', 'Waltham, MA', null, null, null),
  ('university-of-san-diego', 'University of San Diego', 'San Diego, CA', null, null, null),
  ('university-of-south-florida', 'University of South Florida', 'Tampa, FL', null, null, null),
  ('syracuse-university', 'Syracuse University', 'Syracuse, NY', 0.52, 1270, 1440),
  ('arizona-state-university-tempe', 'Arizona State University, Tempe', 'Tempe, AZ', null, null, null),
  ('university-of-central-florida', 'University of Central Florida', 'Orlando, FL', null, null, null),
  ('colorado-college', 'Colorado College', 'Colorado Springs, CO', null, null, null),
  ('university-of-arizona', 'University of Arizona', 'Tucson, AZ', null, null, null),
  ('university-of-oklahoma-norman', 'University of Oklahoma, Norman', 'Norman, OK', null, null, null),
  ('marquette-university', 'Marquette University', 'Milwaukee, WI', null, null, null),
  ('university-of-houston', 'University of Houston', 'Houston, TX', null, null, null),
  ('university-of-missouri-columbia', 'University of Missouri, Columbia', 'Columbia, MO', null, null, null),
  ('auburn-university', 'Auburn University', 'Auburn, AL', null, null, null),
  ('fordham-university', 'Fordham University', 'New York, NY', 0.54, 1320, 1480),
  ('oregon-state-university', 'Oregon State University', 'Corvallis, OR', null, null, null),
  ('cuny-city-college', 'CUNY, The City College of New York', 'New York, NY', null, null, null),
  ('rhodes-college', 'Rhodes College', 'Memphis, TN', null, null, null),
  ('skidmore-college', 'Skidmore College', 'Saratoga Springs, NY', null, null, null),
  ('college-of-new-jersey', 'College of New Jersey', 'Ewing, NJ', null, null, null),
  ('rensselaer-polytechnic-institute', 'Rensselaer Polytechnic Institute', 'Troy, NY', null, null, null),
  ('pepperdine-university', 'Pepperdine University', 'Malibu, CA', 0.32, 1310, 1470),
  ('university-of-texas-dallas', 'University of Texas, Dallas', 'Richardson, TX', null, null, null),
  ('university-of-delaware', 'University of Delaware', 'Newark, DE', null, null, null),
  ('university-of-massachusetts-amherst', 'University of Massachusetts, Amherst', 'Amherst, MA', null, null, null),
  ('dickinson-college', 'Dickinson College', 'Carlisle, PA', null, null, null),
  ('cuny-hunter-college', 'CUNY, Hunter College', 'New York, NY', null, null, null),
  ('university-of-illinois-chicago', 'University of Illinois at Chicago', 'Chicago, IL', null, null, null),
  ('loyola-marymount-university', 'Loyola Marymount University', 'Los Angeles, CA', null, null, null),
  ('university-of-portland', 'University of Portland', 'Portland, OR', null, null, null),
  ('university-at-buffalo-suny', 'University at Buffalo', 'Buffalo, NY', null, null, null),
  ('smith-college', 'Smith College', 'Northampton, MA', null, null, null),
  ('james-madison-university', 'James Madison University', 'Harrisonburg, VA', null, null, null),
  ('san-francisco-state-university', 'San Francisco State University', 'San Francisco, CA', null, null, null),
  ('florida-international-university', 'Florida International University', 'Miami, FL', null, null, null),
  ('louisiana-state-university', 'Louisiana State University', 'Baton Rouge, LA', null, null, null),
  ('kenyon-college', 'Kenyon College', 'Gambier, OH', null, null, null),
  ('american-university', 'American University', 'Washington, DC', null, null, null),
  ('university-of-tennessee-knoxville', 'University of Tennessee, Knoxville', 'Knoxville, TN', null, null, null),
  ('university-of-pittsburgh', 'University of Pittsburgh', 'Pittsburgh, PA', null, null, null),
  ('washington-state-university', 'Washington State University', 'Pullman, WA', null, null, null),
  ('colby-college', 'Colby College', 'Waterville, ME', null, null, null),
  ('drexel-university', 'Drexel University', 'Philadelphia, PA', null, null, null),
  ('tulane-university', 'Tulane University', 'New Orleans, LA', 0.11, 1440, 1530),
  ('university-of-oregon', 'University of Oregon', 'Eugene, OR', null, null, null),
  ('furman-university', 'Furman University', 'Greenville, SC', null, null, null),
  ('stevens-institute-of-technology', 'Stevens Institute of Technology', 'Hoboken, NJ', null, null, null),
  ('university-of-kansas', 'University of Kansas', 'Lawrence, KS', null, null, null),
  ('baylor-university', 'Baylor University', 'Waco, TX', null, null, null),
  ('gonzaga-university', 'Gonzaga University', 'Spokane, WA', null, null, null),
  ('iowa-state-university', 'Iowa State University', 'Ames, IA', null, null, null),
  ('university-of-iowa', 'University of Iowa', 'Iowa City, IA', null, null, null),
  ('suny-geneseo', 'SUNY, Geneseo', 'Geneseo, NY', null, null, null),
  ('university-of-denver', 'University of Denver', 'Denver, CO', null, null, null),
  ('university-of-arkansas', 'University of Arkansas', 'Fayetteville, AR', null, null, null),
  ('elon-university', 'Elon University', 'Elon, NC', null, null, null),
  ('university-of-kentucky', 'University of Kentucky', 'Lexington, KY', null, null, null),
  ('connecticut-college', 'Connecticut College', 'New London, CT', null, null, null),
  ('saint-louis-university', 'Saint Louis University', 'St. Louis, MO', null, null, null),
  ('university-of-south-carolina', 'University of South Carolina', 'Columbia, SC', null, null, null),
  ('cuny-brooklyn-college', 'CUNY, Brooklyn College', 'Brooklyn, NY', null, null, null),
  ('university-of-san-francisco', 'University of San Francisco', 'San Francisco, CA', null, null, null),
  ('worcester-polytechnic-institute', 'Worcester Polytechnic Institute', 'Worcester, MA', null, null, null),
  ('university-of-nevada-reno', 'University of Nevada-Reno', 'Reno, NV', null, null, null),
  ('sonoma-state-university', 'Sonoma State University', 'Rohnert Park, CA', null, null, null),
  ('university-of-dayton', 'University of Dayton', 'Dayton, OH', null, null, null),
  ('depauw-university', 'DePauw University', 'Greencastle, IN', null, null, null),
  ('oklahoma-state-university', 'Oklahoma State University', 'Stillwater, OK', null, null, null),
  ('university-of-hawaii-manoa', 'University of Hawaii, Manoa', 'Honolulu, HI', null, null, null),
  ('manhattan-college', 'Manhattan College', 'Bronx, NY', null, null, null),
  ('towson-university', 'Towson University', 'Towson, MD', null, null, null),
  ('saint-marys-college-of-california', 'Saint Mary''s College of California', 'Moraga, CA', null, null, null),
  ('st-lawrence-university', 'St. Lawrence University', 'Canton, NY', null, null, null),
  ('reed-college', 'Reed College', 'Portland, OR', null, null, null),
  ('kalamazoo-college', 'Kalamazoo College', 'Kalamazoo, MI', null, null, null),
  ('creighton-university', 'Creighton University', 'Omaha, NE', null, null, null),
  ('bryn-mawr-college', 'Bryn Mawr College', 'Bryn Mawr, PA', null, null, null),
  ('university-of-vermont', 'University of Vermont', 'Burlington, VT', null, null, null),
  ('university-of-alabama', 'University of Alabama', 'Tuscaloosa, AL', null, null, null),
  ('kansas-state-university', 'Kansas State University', 'Manhattan, KS', null, null, null),
  ('harvey-mudd-college', 'Harvey Mudd College', 'Claremont, CA', null, null, null),
  ('csu-fresno', 'California State University, Fresno', 'Fresno, CA', null, null, null),
  ('bentley-university', 'Bentley University', 'Waltham, MA', null, null, null),
  ('university-of-california-santa-cruz', 'University of California, Santa Cruz', 'Santa Cruz, CA', null, null, null),
  ('florida-atlantic-university', 'Florida Atlantic University', 'Boca Raton, FL', null, null, null),
  ('university-of-wyoming', 'University of Wyoming', 'Laramie, WY', null, null, null),
  ('wofford-college', 'Wofford College', 'Spartanburg, SC', null, null, null),
  ('university-of-nebraska-lincoln', 'University of Nebraska, Lincoln', 'Lincoln, NE', null, null, null),
  ('temple-university', 'Temple University', 'Philadelphia, PA', null, null, null),
  ('new-jersey-institute-of-technology', 'New Jersey Institute of Technology', 'Newark, NJ', null, null, null),
  ('virginia-military-institute', 'Virginia Military Institute', 'Lexington, VA', null, null, null),
  ('hobart-and-william-smith-colleges', 'Hobart and William Smith Colleges', 'Geneva, NY', null, null, null),
  ('penn-state-university', 'Pennsylvania State University', 'University Park, PA', null, null, null),
  ('oberlin-college', 'Oberlin College', 'Oberlin, OH', null, null, null),
  ('miami-university-oh', 'Miami University (OH)', 'Oxford, OH', null, null, null),
  ('cuny-queens-college', 'CUNY, Queens College', 'Queens, NY', null, null, null),
  ('chapman-university', 'Chapman University', 'Orange, CA', null, null, null)
on conflict (id) do nothing;

-- Verify — how many total colleges now
select count(*) as total_colleges from public.colleges;
